---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: klt-metrics-server
  name: klt-metrics-server
  namespace: keptn-lifecycle-toolkit-system
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      port: metrics
  namespaceSelector:
    matchNames:
      - keptn-lifecycle-toolkit-system
  selector:
    matchLabels:
      control-plane: metrics-operator